repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.3
    hooks:
      - id: uv-export

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: uvx ty check . --ignore unresolved-import
        language: python
